# Generated by Django 3.0.9 on 2020-08-04 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="upvotes_count",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
